server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomDb
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo0NTY3ODkwMTIzNDU2Nzg5MDEyMw==
  expiration: 86400000

# Optional: Customize logging
logging:
  level:
    org.springframework: INFO