server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomDb
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Optional: Customize logging
logging:
  level:
    org.springframework: INFO